<?php require('Views/template/header.phtml'); ?>

<div id="filters" class="bg-shadow">
    <div class="filer-container">
    <button class="btn close-button p-0 d-block" onclick=""><span class="bi bi-x display-5 font-white"></span></button>
    <div class="row d-block">
<?php foreach($view->cardView as $gameData) {
            $gamePrice = "£" . $gameData->getPrice();
            if($gamePrice == "£0"){
                $gamePrice = $gamePrice . ".00";
            }
            $isEnglish = $gameData->getIsEnglish();
            if($isEnglish == "1"){
                $isEnglish = "Yes";
            }
            else {
                $isEnglish = "No";
            }
            $isPhysical = $gameData->getIsPhysical();
            if($isPhysical == "1"){
                $isPhysical = "Yes";
            }
            else {
                $isPhysical = "No";
            }
            echo '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">App ID</span>
            <span class="font-white col-sm-4">'.$gameData->getAppID().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Release date</span>
            <span class="font-white col-sm-4">'.$gameData->getReleaseDate().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">English</span>
            <span class="font-white col-sm-4">'.$isEnglish.'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Developer</span>
            <span class="font-white col-sm-4">'.$gameData->getDeveloper().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Publisher</span>
            <span class="font-white col-sm-4">'.$gameData->getPublisher().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Platforms</span>
            <span class="font-white col-sm-4">'.$gameData->getPlatforms().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Required age</span>
            <span class="font-white col-sm-4">'.$gameData->getRequiredAge().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Categories</span>
            <span class="font-white col-sm-4">'.$gameData->getCategories().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Genres</span>
            <span class="font-white col-sm-4">'.$gameData->getGenres().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Tags</span>
            <span class="font-white col-sm-4">'.$gameData->getTags().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Achievements</span>
            <span class="font-white col-sm-4">'.$gameData->getAchievements().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Positive ratings</span>
            <span class="font-white col-sm-4">'.$gameData->getPositiveRatings().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Negative ratings</span>
            <span class="font-white col-sm-4">'.$gameData->getNegative_Ratings().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Average playtime</span>
            <span class="font-white col-sm-4">'.$gameData->getAveragePlaytime().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Median playtime</span>
            <span class="font-white col-sm-4">'.$gameData->getMedianPlaytime().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Physical</span>
            <span class="font-white col-sm-4">'.$isPhysical.'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Units available</span>
            <span class="font-white col-sm-4">'.$gameData->getUnitsAvailable().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Units sold</span>
            <span class="font-white col-sm-4">'.$gameData->getUnitsSold().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row py-2 m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Price</span>
            <span class="font-white col-sm-4">'.$gamePrice.'</span>
            <span class="col-sm-2"></span>
            </div>'
        ;} 
        ?>
    </div>
    <div class="d-flex justify-content-between">
    <button class="btn close-button p-0 m-3" onclick=""><span class="bi bi-arrow-left-circle-fill display-5 font-white"></span></button>
    <button class="btn close-button p-0 m-3" onclick=""><span class="bi bi-arrow-right-circle-fill display-5 font-white"></span></button>
        </div>
</div>
</div>
<?php require('Views/template/footer.phtml'); ?>