<?php require('template/header.phtml') ?>

<div class="row">
        <?php foreach($view->gameDataSet as $gameData) {
            $gamePrice = "£" . $gameData->getPrice();
            if($gamePrice == "£0"){
                $gamePrice = $gamePrice . ".00";
            }
            echo '
            <div class="width-23 mx-auto my-1 p-0 text-center bg-bl radius-border font-xs">
                <div class="row font-white glow-border m-0 p-0">
                    <div class="col-sm-6 my-1 p-0">
                        <p>ID</p>
                        <p class="font-blue font-bold">'.$gameData->getAppID().'</p>
                    </div>
                    <div class="col-sm-6 my-1 p-0">
                        <p>Status</p>
                        <p class="font-blue font-bold">'.$gameData->getStatus().'</p>
                    </div>
                    <div class="col-sm-12 my-1 p-0">
                        <p>Units available</p>
                        <p class="font-blue font-bold">'.$gameData->getUnitsAvailable().'</p>
                    </div>
                    <div class="col-sm-12 my-1 p-0">
                        <p>Units sold</p>
                        <p class="font-blue font-bold">'.$gameData->getUnitsSold().'</p>
                    </div>
                    <div class="w-75 col-sm-12 mx-auto py-2 d-flex justify-content-between border-top">
                        <span>Price</span>
                        <span class="font-blue font-bold">'.$gamePrice.'</span>
                    </div>
                </div>
            </div>';
        }
        ?>
</div>

<?php require('template/footer.phtml') ?>