<?php require('template/header.phtml') ?>
<div class="row justify-content-md-center m-0">
        <?php $index= 1;
         foreach($view->gameDataSet as $gameData) {
            echo '
            <div class="width-23 mx-auto my-1 p-0 text-center bg-bl radius-border font-xs">
                <div class="row font-white glow-border m-0 p-0">
                    <div class="col-sm-6 my-1 p-0">
                        <p>ID</p>
                        <p class="font-blue font-bold">'.$gameData->getAppID().'</p>
                    </div>
                    <div class="col-sm-6 my-1 p-0">
                        <p>Release date</p>
                        <p class="font-blue font-bold">'.$gameData->getReleaseDate().'</p>
                    </div>                    
                    <div class="col-sm-12 my-1 p-0">
                        <p>Average playtime vs Median playtime</p>
                        <script type="text/javascript">
                        var YvalueA = "' . $gameData->getAveragePlaytime() . '";
                        var YvalueB = "' . $gameData->getMedianPlaytime() . '";
                        </script>
                        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
                        <canvas id="myChart' . $index . '" style="width:100%;max-width:400px"></canvas>
                        
                        <script>
                        var xValues = ["Average Playtime", "Median Playtime"];
                        var yValues = [YvalueA, YvalueB];
                        
                        var barColors = [
                        "#b91d47",
                        "#00aba9"
                        ];
                        
                        new Chart("myChart' . $index . '", {
                        type: "pie",
                        data: {
                        labels: xValues,
                        datasets: [{
                        backgroundColor: barColors,
                        data: yValues
                        }]
                        },
                        options: {
                            responsive: true
                        }
                        });
                        </script>
                    </div>
                    <div class="w-75 col-sm-12 mx-auto py-2 d-flex justify-content-between border-top">
                        <span>Units sold</span>
                        <span class="font-blue font-bold">'.$gameData->getUnitsSold().'</span>
                    </div>
                </div>
            </div>';
            $index++;
        }
        ?>
    </div>
<?php require('template/footer.phtml') ?>