<?php require('Views/template/header.phtml'); ?>
<div class="row justify-content-md-center m-0">
        <?php foreach($view->gameDataSet as $gameData) {
            $gamePrice = "£" . $gameData->getPrice();
            if($gamePrice == "£0"){
                $gamePrice = $gamePrice . ".00";
            }
            echo '
            <div class="width-23 mx-auto h-25 my-1 p-0 text-center bg-bl radius-border font-xs">
                <div class="row font-white glow-border m-0 p-0">
                    <div class="col-sm-6 my-1 p-0">
                        <p>ID</p>
                        <p class="font-blue font-bold">'.$gameData->getAppID().'</p>
                    </div>
                    <div class="col-sm-6 my-1 p-0">
                        <p>Developer</p>
                        <p class="font-blue font-bold">'.$gameData->getDeveloper().'</p>
                    </div>                    
                    <div class="col-sm-12 my-1 p-0">
                        <p>Positive vs Negative Ratings</p>
                        <script type="text/javascript">
                        var YvalueA = "' . $gameData->getPositiveRatings() . '";
                        var YvalueB = "' . $gameData->getNegative_Ratings() . '";
                        </script>
                        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
                        <canvas id="myChart' . $index . '" style="width:100%;max-width:400px"></canvas>
                        
                        <script>
                        var xValues = ["Positive Ratings", "Negative Ratings"];
                        var yValues = [YvalueA, YvalueB];
                        
                        var barColors = [
                        "#b91d47",
                        "#00aba9"
                        ];
                        
                        new Chart("myChart' . $index . '", {
                        type: "bar",
                        data: {
                        labels: xValues,
                        datasets: [{
                        backgroundColor: barColors,
                        data: yValues
                        }]
                        },
                        options: {
                            responsive: true,
                            legend: {display: false},
                        }
                        });
                        </script>
                    </div>
                    <div class="w-75 col-sm-12 mx-auto py-2 d-flex justify-content-between border-top">
                        <span>Price</span>
                        <span class="font-blue">'.$gamePrice.'</span>
                    </div>
                </div>
            </div>';
            $index++;
        }
        ?>
    </div>
<?php require('Views/template/footer.phtml'); ?>