<?php 
    foreach ($view->cardView as $gameData) {
        $gamePrice = "£" . $gameData->getPrice();
            if($gamePrice == "£0"){
                $gamePrice = $gamePrice . ".00";
            }
            $isEnglish = $gameData->getIsEnglish();
            if($isEnglish == "1"){
                $isEnglish = "Yes";
            }
            else {
                $isEnglish = "No";
            }
            $isPhysical = $gameData->getIsPhysical();
            if($isPhysical == "1"){
                $isPhysical = "Yes";
            }
            else {
                $isPhysical = "No";
            }
            echo '
            <div id="cardView" class="bg-shadow">
            <div class="filer-container p-0">
            <button class="btn close-button p-0 d-block" onclick="hideCard();return false;"><span class="bi bi-x display-5 font-white"></span></button>
            <div class="row d-block">';            
            echo '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">App ID</span>
            <span class="font-white col-sm-4">'.$gameData->getAppID().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Release date</span>
            <span class="font-white col-sm-4">'.$gameData->getReleaseDate().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">English</span>
            <span class="font-white col-sm-4">'.$isEnglish.'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Developer</span>
            <span class="font-white col-sm-4">'.$gameData->getDeveloper().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Publisher</span>
            <span class="font-white col-sm-4">'.$gameData->getPublisher().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Platforms</span>
            <span class="font-white col-sm-4">'.$gameData->getPlatforms().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Required age</span>
            <span class="font-white col-sm-4">'.$gameData->getRequiredAge().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Categories</span>
            <span class="font-white col-sm-4 over-flow">'.$gameData->getCategories().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Genres</span>
            <span class="font-white col-sm-4">'.$gameData->getGenres().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Tags</span>
            <span class="font-white col-sm-4">'.$gameData->getTags().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Achievements</span>
            <span class="font-white col-sm-4">'.$gameData->getAchievements().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Positive ratings</span>
            <span class="font-white col-sm-4">'.$gameData->getPositiveRatings().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Negative ratings</span>
            <span class="font-white col-sm-4">'.$gameData->getNegative_Ratings().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Average playtime</span>
            <span class="font-white col-sm-4">'.$gameData->getAveragePlaytime().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Median playtime</span>
            <span class="font-white col-sm-4">'.$gameData->getMedianPlaytime().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Physical</span>
            <span class="font-white col-sm-4">'.$isPhysical.'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Units available</span>
            <span class="font-white col-sm-4">'.$gameData->getUnitsAvailable().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Units sold</span>
            <span class="font-white col-sm-4">'.$gameData->getUnitsSold().'</span>
            <span class="col-sm-2"></span>
            </div>'.
            '<div class="col-sm-12 row m-0">
            <span class="col-sm-2"></span>
            <span class="font-blue col-sm-4">Price</span>
            <span class="font-white col-sm-4">'.$gamePrice.'</span>
            <span class="col-sm-2"></span>
            </div>'
        ; 
        echo '
            </div>
            <div class="row mx-0 my-1">
            <span class="col-sm-2"></span>
            <button class="col-sm-3 my-1 btn font-grey bg-bright p-0" onclick="hideCard()"><span class="bi bi-x-circle-fill"></span></button>
            <span class="col-sm-2"></span>
            <form class="col-sm-3 p-0 my-1" action="/cardViewTest.php" method="post">
            <button class="btn font-blue bg-bright p-0 h-100 w-100 m-0" name="action" value="edit" ><span class="bi bi-gear-fill"></span></button>
            <input type="hidden" name="id" value="'.$gameData->getAppID().'"/>
            </form>
            <span class="col-sm-2"></span>
            </div>
            <div class="d-flex justify-content-between">';
               
            if ($gameData->getAppID() > 10) {
                echo '<button class="btn close-button p-0 m-3" onclick='."'".'cardView('.'"view",'.($gameData->getAppID() - 10).')'."'".'><span class="bi bi-arrow-left-circle-fill display-5 font-white"></span></button>';
                }
                else {
                    echo '<button type="button" class="btn close-button p-0 m-3" onclick="" disabled><span class="bi bi-arrow-left-circle display-5 font-grey"></span></button>';
                }
                echo'
                <button class="btn close-button p-0 m-3" onclick='."'".'cardView('.'"view",'.($gameData->getAppID() + 10).')'."'".'><span class="bi bi-arrow-right-circle-fill display-5 font-white"></span></button>';
            echo '
            </div>
            </div>
            </div>';
        }