<link href="/css/my-style.css" rel="stylesheet">
<link href="/css/bootstrap.css" rel="stylesheet">
<link href="/css/bootstrap.rtl.css" rel="stylesheet">
<link href="/css/bootstrap-grid.css" rel="stylesheet">
<link href="/css/bootstrap-grid.rtl.css" rel="stylesheet">
<link href="/css/bootstrap-reboot.css" rel="stylesheet">
<link href="/css/bootstrap-reboot.rtl.css" rel="stylesheet">
<link href="/css/bootstrap-utilities.css" rel="stylesheet">
<link href="/css/bootstrap-utilities.rtl.css" rel="stylesheet">
<link href="/css/bootstrap-tagsinput.css" rel="stylesheet">
<link href="/css/bootstrap-tagsinput.less" rel="stylesheet">
<link href="/css/animate.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="/js/jQuery.js"></script>
<script type="text/javascript" src="/js/bootstrap.bundle.js"></script>
<script type="text/javascript" src="/js/bootstrap.esm.js"></script>
<script type="text/javascript" src="/js/bootstrap.js"></script>
<script type="text/javascript" src="/js/bootstrap-tagsinput.min.js"></script>
<script type="text/javascript" src="/js/bootstrap-tagsinput.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script type="text/javascript" src="/js/custom-js.js"></script>
<script type="text/javascript" src="/js/lazyLoad.js"></script>
<?php
$platforms = array("windows", "mac", "linux");
$status = array("In-Development", "Restricted", "Archived", "Live", "Banned", "Beta");
$age = array("0", "12", "16", "18");
foreach ($view->cardView as $gameData) {
        $isEnglish = $gameData->getIsEnglish();
        if($isEnglish == "1"){
            $isEnglish = "Yes";
        }
        else {
            $isEnglish = "No";
        }
        $isPhysical = $gameData->getIsPhysical();
        if($isPhysical == "1"){
            $isPhysical = "Yes";
        }
        else {
            $isPhysical = "No";
        }
        $platformsString = strval($gameData->getPlatforms());
        echo '
        <form method="POST" action="/cardViewTest.php">
        <div id="cardView" class="bg-shadow">
        <div class="filer-container p-0">';
        if ($view->succesfullEdit) {
            echo '<span class="font-blue text-center">Changes applied</span>';
        }
        if (!$view->succesfullEdit) {
            echo '<span class="font-blue text-center">Something went wrong</span>';
        }
        echo '<button class="btn close-button p-0 d-block" onclick="hideCard();return false;"><span class="bi bi-x display-5 font-white"></span></button>
        <div class="row d-block m-0">';            
        echo '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">App ID</span>
        <span class="font-white col-sm-4">'.$gameData->getAppID().'</span>
        <input type="hidden" name="appID" id="e1" class="font-white col-sm-4" value="'.$gameData->getAppID().'" />
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Release date</span>
        <input type="date" name="releaseDate2" id="e2" class="font-white col-sm-4" value="'.$gameData->getReleaseDate().'" />
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">English</span>
        <div class="col-sm-4 row text-center m-0 bg-trans">';
        if ($isEnglish == "Yes") {
            echo '<input type="radio" name="isEnglish2" checked id="e-yes2"  value="1" class="col-sm-1 p-0 m-auto"/>
        <label for="e-yes2" id="yes-lbl" class="col-sm-6 p-0 font-white">Yes</label>
        <input type="radio" id="e-no2" name="isEnglish2"  value="0" class="col-sm-1 p-2 m-auto"/>
        <label for="e-no2" id="no-lbl"  class="col-sm-6 p-0 font-white">No</label>';
        }
        if ($isEnglish == "No") {
            echo '<input type="radio" name="isEnglish2" id="e-yes2" value="1" class="col-sm-1 p-0 m-auto"/>
            <label for="e-yes2" id="yes-lbl" class="col-sm-6 p-0 font-white">Yes</label>
            <input type="radio" id="e-no2" name="isEnglish2" checked value="0" class="col-sm-1 p-2 m-auto"/>
            <label for="e-no2" id="no-lbl" class="col-sm-6 p-0 font-white">No</label>';
        }
        echo '                
        </div>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Developer</span>
        <div class="col-sm-4 bg-trans">
        <input type="text" name="developer2" value="'.$gameData->getDeveloper().'" data-role="tagsinput" />
        <span class="col-sm-2"></span>
        </div></div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Publisher</span>
        <div class="col-sm-4 bg-trans">
        <input type="text" name="publisher2" value="'.$gameData->getPublisher().'" data-role="tagsinput" />
        </div>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Platforms</span>
        <div class="col-sm-4 row text-center m-0 bg-trans">';
        foreach ($platforms as $value) {
            echo '<input type="checkbox" name="platforms2[]" id="'.$value.'2" value="'.$value.'"';
            if (strstr($platformsString, $value)) {
                echo 'checked';
            }
            echo '/><label for="'.$value.'2" class="font-white mx-auto my-1">'.$value.'</label>';
        }
        echo'
        </div>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Status</span>
        <div class="col-sm-4 row text-center m-0 bg-trans">';
        foreach ($status as $value) {
            echo '<input type="radio" name="status2" id="'.$value.'2" value="'.$value.'"';
            if ($value == $gameData->getStatus()) {
                echo ' checked ';
            }
            echo '/><label for="'.$value.'2" class="font-white mx-auto">'.$value.'</label>';
        }
        echo'
        </div>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Required age</span>
        <div class="col-sm-4 row text-center m-0 bg-trans">';
        foreach ($age as $value) {
            echo '<input type="radio" name="requiredAge2" id="'.$value.'2" name="age2" value="'.$value.'"';
            if ($value == $gameData->getRequiredAge()) {
                echo ' checked ';
            }
            echo '/><label for="'.$value.'2" class="font-white mx-auto">'.$value.'</label>';
        }
        echo'
        <span class="col-sm-2"></span>
        </div>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Categories</span>
        <div class="col-sm-4 bg-trans">
        <input type="text" name="categories2" value="'.$gameData->getCategories().'" data-role="tagsinput" />
        </div>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Genres</span>
        <div class="col-sm-4 bg-trans">
        <input type="text" name="genres2" value="'.$gameData->getGenres().'" data-role="tagsinput" />
        </div>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Tags</span>
        <div class="col-sm-4 bg-trans">
        <input type="text" name="tags2" value="'.$gameData->getTags().'" data-role="tagsinput" />
        </div>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Achievements</span>
        <input type="text" name="numberOfAchievements2" class="font-white col-sm-4" value="'.$gameData->getAchievements().'"/>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Positive ratings</span>
        <input type="text" name="positiveRatings2" class="font-white col-sm-4" value="'.$gameData->getPositiveRatings().'"/>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Negative ratings</span>
        <input type="text" name="negativeRatings2" class="font-white col-sm-4" value="'.$gameData->getNegative_Ratings().'"/>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Average playtime</span>
        <input type="text" name="avgPlaytime2" class="font-white col-sm-4" value="'.$gameData->getAveragePlaytime().'"/>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Median playtime</span>
        <input type="text" name="medianPlaytime2" class="font-white col-sm-4" value="'.$gameData->getMedianPlaytime().'"/>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Physical</span>
        <div class="col-sm-4 row text-center m-0 bg-trans">';
        if ($isPhysical == "Yes") {
            echo '<input type="radio" checked id="p-yes2" name="physical2" value="1" class="col-sm-1 p-0 m-auto"/>
        <label for="p-yes2" id="yes-lbl" class="col-sm-6 p-0 font-white">Yes</label>
        <input type="radio" id="p-no2" name="physical2" value="0" class="col-sm-1 p-2 m-auto"/>
        <label for="p-no2" id="no-lbl" class="col-sm-6 p-0 font-white">No</label>';
        }
        if ($isPhysical == "No") {
            echo '<input type="radio" id="p-yes2" name="physical2" value="1" class="col-sm-1 p-0 m-auto"/>
            <label for="p-yes2" id="yes-lbl" class="col-sm-6 p-0 font-white">Yes</label>
            <input type="radio" id="p-no2" checked name="physical2" value="0" class="col-sm-1 p-2 m-auto"/>
            <label for="p-no2" id="no-lbl" class="col-sm-6 p-0 font-white">No</label>';
        }
        echo '                
        <span class="col-sm-2"></span>
        </div></div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Units available</span>
        <input type="text" name="numberOfUnitsAvail2" class="font-white col-sm-4" value="'.$gameData->getUnitsAvailable().'"/>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Units sold</span>
        <input type="text" name="unitsSold2" class="font-white col-sm-4" value="'.$gameData->getUnitsSold().'"/>
        <span class="col-sm-2"></span>
        </div>'.
        '<div class="col-sm-12 row m-1">
        <span class="col-sm-2"></span>
        <span class="font-blue col-sm-4">Price</span>
        <input type="text" name="pricePerUnit2" class="font-white col-sm-4" value="'.$gameData->getPrice().'"/>
        <span class="col-sm-2"></span>
        </div>
        </div>
        <div class="row m-0">
    <span class="col-sm-2"></span>
    <button class="col-sm-3 p-1 my-3 btn font-grey bg-bright" onclick="hideCard();return false;"><span class="bi bi-x-octagon-fill"></span></button>
    <span class="col-sm-2"></span>
    <button class="col-sm-3 my-3 p-1 btn font-blue bg-bright" onclick='."'".'cardView('.'"edit2",'.$gameData->getAppID().';return false;)'."'".'><span class="bi bi-save-fill"></span></button>
    <span class="col-sm-2"></span>
    </div>
    </form>'
    ;}
