<?php require('Views/template/header.phtml') ?>
<?php require_once('Models/Filter.php')?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    </nav>
    </header>
<main>
<div class="container my-3 glow-border p-3 animate__animated animate__rollIn animate__fadeIn">
  <div class="row justify-content-md-center m-0">
    <div class="col-md-5 mx-1 my-3 text-center bg-bl radius-border font-xs glow-border animate__animated animate__fadeIn animate__slow">
      <!-- php foreach($view->genreDataSet as $Genre) {
            $gameData->getGenreName() . '</td> <td>' .
            $gameData->getGameNumber() . '</td></tr>' .
        }

        ?> -->
        
        <h3>Top Five Genres</h3>
        <script type="text/javascript">  
        <?php
            $yValue=1;
                foreach($view->genreDataSet as $genreData)
              {
                echo'var Yvalue' . $yValue . '  = "' . $genreData->getGameNumber() . '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->genreDataSet as $genreData)
            {
              echo'var Xvalue' . $xValue . '  = "' . $genreData->getGenreName() . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>
      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script> -->
      <canvas id="myChart" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = [Xvalue1, Xvalue2, Xvalue3, Xvalue4, Xvalue5];
      var yValues = [Yvalue1, Yvalue2, Yvalue3, Yvalue4, Yvalue5];
      //var yValues = [80,55];
      var barColors = [
        "#b91d47",
        "#00aba9",
        "#244CEB",
        "#DB0C02",
        "#F58E20"
      ];

      var chart = new Chart("myChart", {
        type: "bar",
        data: {
          labels: xValues,
          datasets: [{
            backgroundColor: barColors,
            data: yValues

          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index;
          var  data = chart.data.labels[selectedIndex];
          window.location.href = "/salesRep.php?submitFilterOptions=&genreInput=" + data;
          },
          responsive: true,
          legend: {
            display: false,
         },
         scales: {
            yAxes: [{ticks: {
                    fontColor: 'white'
                },
              scaleLabel: {
                display: true,
                labelString: 'No. of Games',
                fontColor: 'white'
              }
            }],
            xAxes: [{
              ticks: {
                    fontColor: 'white'
                },
              scaleLabel: {
                display: true,
                labelString: 'Genres',
                fontColor: 'white'
              }
            }]
          }
        }
      });
      </script>
     </div>    
    </div>
    <div class="col-md-1"></div>
     <div class="col-md-5 mx-1 my-3 text-center bg-bl radius-border font-xs glow-border animate__animated animate__fadeIn animate__slow" >
      <h3>Top Five Developers by Games Available</h3>
      <script type="text/javascript">  
        <?php
            $yValue=1;
                foreach($view->developerDataSet as $developerData)
              {
                echo'var Yvalue' . $yValue . '  = "' . $developerData->getGamesPerDeveloper() . '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->developerDataSet as $developerData)
            {
              echo'var Xvalue' . $xValue . '  = "' . ucwords($developerData->getDeveloperName()) . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>      
      <canvas id="myChartB" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = ["Choice of Games", "Koei Tecmo Games Co., Ltd.", "Ripknot Systems", "Laush Dmitriy Sergeevich", "Nikita 'Ghost_Rus'"];
      //var xValues = [Xvalue1, Xvalue2, Xvalue3, Xvalue4, Xvalue5];
      var yValues = [Yvalue1, Yvalue2, Yvalue3, Yvalue4, Yvalue5];      
      var barColors = [
        "#b91d47",
        "#00aba9",
        "#244CEB",
        "#DB0C02",
        "#F58E20"
      ];

      var chartb = new Chart("myChartB", {
        type: "doughnut",
        data: {
          labels: xValues,
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index; 
          var data = chartb.data.labels[selectedIndex];
          window.location.href = "/developer.php?submitFilterOptions=&developerInput=" + data;
          },
          responsive: true,
          legend: {
             labels: {
                  fontColor: 'white'
                 }
              },
            }
        
      });
      </script>
      </div>
    </div>

    <div class="w-100"></div>
  
    <div class="col-sm-5 mx-1 my-3 text-center bg-bl radius-border font-xs glow-border animate__animated animate__fadeIn animate__slow">
    <h3>Top Five Publishers by Games Available</h3>
    <script type="text/javascript">  
        <?php
            $yValue=1;
                foreach($view->publisherDataSet as $publisherData)
              {
                echo'var Yvalue' . $yValue . '  = "' . $publisherData->getGamesPerPublisher() . '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->publisherDataSet as $publisherData)
            {
              echo'var Xvalue' . $xValue . '  = "' . ucfirst(strtolower($publisherData->getPublisherName())) . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>      
      <canvas id="myChartC" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = [Xvalue1, Xvalue2, Xvalue3, Xvalue4, Xvalue5];
      var yValues = [Yvalue1, Yvalue2, Yvalue3, Yvalue4, Yvalue5];      
      var barColors = [
        "#b91d47",
        "#00aba9",
        "#244CEB",
        "#DB0C02",
        "#F58E20"
      ];

      var chartc = new Chart("myChartC", {
        type: "bar",
        data: {
          labels: xValues, 
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index; 
          var data = chartc.data.labels[selectedIndex];
          window.location.href = "/developer.php?submitFilterOptions=&publisherInput=" + data;
          },
          responsive: true,
          legend: {
            display: false,
            
         },
         scales: {
            yAxes: [{
              ticks: {
                    fontColor: 'white'
                },
              scaleLabel: {
                display: true,
                labelString: 'No. of Available Games',
                fontColor: 'white'
              }
            }],
            xAxes: [{
              ticks: {
                 fontColor: 'white'
              },
              scaleLabel: {
                display: true,
                labelString: 'Publishers',
                fontColor: 'white'
              }
            }]
          }
        }
      });
      </script>
    </div>
    </div>
    <div class="col-md-1"></div>
    <div class="col-sm-5 mx-1 my-3 text-center bg-bl radius-border font-xs glow-border animate__animated animate__fadeIn animate__slow">
    <h3>OS Compatibility</h3>
        
      <script type="text/javascript">  
        <?php
            $yValue=1;
            $symbol="%";
                foreach($view->platformDataSet as $platformData)
              {
                $percent = round(($platformData->getPlatformNumber()/$view->total)*100, 2);
            $symbol="%";
                echo'var Yvalue' . $yValue . '  = "' . $percent  .   '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->platformDataSet as  $platformData)
            {
              echo'var Xvalue' . $xValue . '  = "' . ucwords($platformData->getPlatform()) . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>      
      <canvas id="myChartZ" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = [Xvalue1, Xvalue2, Xvalue3];
      var yValues = [Yvalue1, Yvalue2, Yvalue3];      
      var barColors = [
        "#b91d47",
        "#00aba9",
        "#244CEB"
      ];

      var chartd = new Chart("myChartZ", {
        type: "pie",
        data: {
          labels: xValues,
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index; 
          var data = chartd.data.labels[selectedIndex];
          window.location.href = "/proofReader.php?submitFilterOptions=&platforms=" + data;
          },
          responsive: true,
          legend: {
             labels: {
                  fontColor: 'white'
                 }
              },
          tooltips: {
          enabled: true,
          mode: 'single',
          callbacks: {
          label: function (tooltipItems, data) {
            var i = tooltipItems.index;
            return data.labels[i] + ": " + data.datasets[0].data[i] + "%";
                        }
            } 
          }         
        }
      });
      </script>


    </div>
    </div>
  </div>
</div>
<?php require('Views/template/footer.phtml') ?>