<?php require('Views/template/header.phtml') ?>
<div class="container">
  <div class="row justify-content-md-center m-0">
    <div class="col-md-6 my-2 text-center bg-bl radius-border font-xs glow-border">
      <!-- php foreach($view->genreDataSet as $Genre) {
            $gameData->getGenreName() . '</td> <td>' .
            $gameData->getGameNumber() . '</td></tr>' .
        }

        ?> -->
        <h3>Top Five Genres<h3>
        <script type="text/javascript">  
        <?php
            $yValue=1;
                foreach($view->genreDataSet as $genreData)
              {
                echo'var Yvalue' . $yValue . '  = "' . $genreData->getGameNumber() . '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->genreDataSet as $genreData)
            {
              echo'var Xvalue' . $xValue . '  = "' . $genreData->getGenreName() . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
      <canvas id="myChart" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = [Xvalue1, Xvalue2, Xvalue3, Xvalue4, Xvalue5];
      var yValues = [Yvalue1, Yvalue2, Yvalue3, Yvalue4, Yvalue5];
      //var yValues = [80,55];
      var barColors = [
        "#b91d47",
        "#00aba9",
        "#244CEB",
        "#DB0C02",
        "#F58E20"
      ];

      var chart = new Chart("myChart", {
        type: "bar",
        data: {
          labels: [Xvalue1, Xvalue2, Xvalue3, Xvalue4, Xvalue5],
          datasets: [{
            backgroundColor: barColors,
            data: yValues

          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index; 
          alert(chart.data.labels[selectedIndex]);
          //console.log(chart.data.labels[selectedIndex]);    
          },
          responsive: true,
          legend: {
            display: false,
         },
         scales: {
            yAxes: [{ticks: {
                    fontColor: 'white'
                },
              scaleLabel: {
                display: true,
                labelString: 'Game',
                fontColor: 'white'
              }
            }],
            xAxes: [{
              ticks: {
                    fontColor: 'white'
                },
              scaleLabel: {
                display: true,
                labelString: 'Genre',
                fontColor: 'white'
              }
            }]
          }
        }
      });
      </script>
     </div>
    </div>
     <div class="col-md-6 my-2 text-center bg-bl radius-border font-xs glow-border" >
      <h3>Top Five Developers by Games Available</h3>
      <script type="text/javascript">  
        <?php
            $yValue=1;
                foreach($view->developerDataSet as $developerData)
              {
                echo'var Yvalue' . $yValue . '  = "' . $developerData->getGamesPerDeveloper() . '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->genreDataSet as $genreData)
            {
              echo'var Xvalue' . $xValue . '  = "' . $genreData->getGenreName() . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
      <canvas id="myChartB" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = ["CHOICE OF GAMES", "KOEI TECMO GAMES CO., LTD.", "RIPKNOT SYSTEMS", "LAUSH DMITRIY SERGEEVICH", "NIKITA 'GHOST_RUS'"];
      var yValues = [Yvalue1, Yvalue2, Yvalue3, Yvalue4, Yvalue5];
      //var yValues = [80,55];
      var barColors = [
        "#b91d47",
        "#00aba9",
        "#244CEB",
        "#DB0C02",
        "#F58E20"
      ];

      var chartb = new Chart("myChartB", {
        type: "doughnut",
        data: {
          labels: ["CHOICE OF GAMES", "KOEI TECMO GAMES CO., LTD.", "RIPKNOT SYSTEMS", "LAUSH DMITRIY SERGEEVICH", "NIKITA 'GHOST_RUS'"],
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index; 
          alert(chartb.data.labels[selectedIndex]);
          //console.log(chart.data.labels[selectedIndex]);    
          },
          responsive: true,
          legend: {
             labels: {
                  fontColor: 'white'
                 }
              },
          
        
      });
      </script>
      </div>
    </d)v>

    <div class="w-100"></div>

    <div class="col-sm-6 my-2 text-center bg-bl radius-border font-xs glow-border">
    <h3>Top Five Publishers by Games Available</h3>
    <script type="text/javascript">  
        <?php
            $yValue=1;
                foreach($view->publisherDataSet as $publisherData)
              {
                echo'var Yvalue' . $yValue . '  = "' . $publisherData->getGamesPerPublisher() . '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->publisherDataSet as $publisherData)
            {
              echo'var Xvalue' . $xValue . '  = "' . $publisherData->getPublisherName() . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
      <canvas id="myChartC" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = [Xvalue1, Xvalue2, Xvalue3, Xvalue4, Xvalue5];
      var yValues = [Yvalue1, Yvalue2, Yvalue3, Yvalue4, Yvalue5];
      //var yValues = [80,55];
      var barColors = [
        "#b91d47",
        "#00aba9",
        "#244CEB",
        "#DB0C02",
        "#F58E20"
      ];

      var chartc = new Chart("myChartC", {
        type: "bar",
        data: {
          labels: [Xvalue1, Xvalue2, Xvalue3, Xvalue4, Xvalue5], 
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index; 
          alert(chartc.data.labels[selectedIndex]);
          //console.log(chart.data.labels[selectedIndex]);    
          },
          responsive: true,
          legend: {
            display: false,
            
         },
         scales: {
            yAxes: [{
              ticks: {
                    fontColor: 'white'
                },
              scaleLabel: {
                display: true,
                labelString: 'Game Uni',
                fontColor: 'white'
              }
            }],
            xAxes: [{
              ticks: {
                 fontColor: 'white'
              },
              scaleLabel: {
                display: true,
                labelString: 'Publisher',
                fontColor: 'white'
              }
            }]
          }
        }
      });
      </script>
    </div>
    </div>
    
    <div class="col-sm-6 my-2 text-center bg-bl radius-border font-xs glow-border">
    <h3>OS Compatibility</h3>
        <?php  foreach($view->platformDataSet as $platformData)
                  {
                    $total = $total + $platformData->getPlatformNumber();
                  }
                  ?>
      <script type="text/javascript">  
        <?php
            $yValue=1;
            $symbol="%";
                foreach($view->platformDataSet as $platformData)
              {
                $percent = round(($platformData->getPlatformNumber()/$total)*100, 2);
            $symbol="%";
                echo'var Yvalue' . $yValue . '  = "' . $percent  .   '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->platformDataSet as  $platformData)
            {
              echo'var Xvalue' . $xValue . '  = "' . $platformData->getPlatform() . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
      <canvas id="myChartZ" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = [Xvalue1, Xvalue2, Xvalue3];
      var yValues = [Yvalue1, Yvalue2, Yvalue3];
      //var yValues = [80,55];
      var barColors = [
        "#b91d47",
        "#00aba9",
        "#244CEB"
      ];

      var chartd = new Chart("myChartZ", {
        type: "pie",
        data: {
          labels: [Xvalue1, Xvalue2, Xvalue3],
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index; 
          alert(chartd.data.labels[selectedIndex]);
          //console.log(chart.data.labels[selectedIndex]);    
          },
          responsive: true,
          legend: {
             labels: {
                  fontColor: 'white'
                 }
              },
          tooltips: {
          enabled: true,
          mode: 'single',
          callbacks: {
          label: function (tooltipItems, data) {
            var i = tooltipItems.index;
            return data.labels[i] + ": " + data.datasets[0].data[i] + "%";
        }
    } 
}
         
        }
      });
      </script>


    </div>
    </div>
  </div>
</div>
<?php require('Views/template/footer.phtml') ?>