<?php require('Views/template/header.phtml'); ?>
<div class="row justify-content-md-center m-0">
        <?php foreach($view->gameDataSet as $gameData) {
            echo '
            <div class="width-23 h-25 mx-auto my-1 p-0 text-center bg-bl radius-border font-xs" onclick="cardView('.$gameData->getAppID().')">
                <div class="row font-white glow-border h-25 m-0 p-0">
                    <div class="col-sm-6 my-1 p-0">
                        <p>ID</p>
                        <p class="font-blue">'.$gameData->getAppID().'</p>
                    </div>
                    <div class="col-sm-6 my-1 p-0">
                        <p>Status</p>
                        <p class="font-blue">'.$gameData->getStatus().'</p>
                    </div>
                    <div class="col-sm-12 my-1 p-0">
                        <p>Categories</p>
                        <p class="font-blue">'.$gameData->getCategories().'</p>
                    </div>
                    <div class="col-sm-12 my-1 p-0">
                        <p>Tags</p>
                        <p class="font-blue">'.$gameData->getTags().'</p>
                    </div>
                    <div class="w-75 col-sm-12 mx-auto py-2 d-flex justify-content-between border-top">
                        <span>Genres</span>
                        <span class="font-blue">'.$gameData->getGenres().'</span>
                    </div>
                </div>
            </div>';
        }
        ?>
    </div>
<?php require('Views/template/footer.phtml'); ?>