<?php require('Views/template/header.phtml'); ?>

<h3>Test</h3>

<?php  //foreach($view->platformDataSet as $platformData)
              {
               // $total = $total + $platformData->getPlatformNumber();
              }
               echo '<h3>' . $total . '</h3>'?>
               


<script type="text/javascript">  
        <?php
            $yValue=1;
                foreach($view->platformDataSet as $platformData)
              {
                $percent = round(($platformData->getPlatformNumber()/$view->total)*100, 2);
                echo'var Yvalue' . $yValue . '  = "' . $percent. '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->platformDataSet as  $platformData)
            {
              echo'var Xvalue' . $xValue . '  = "' . $platformData->getPlatform() . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
      <canvas id="myChartZ" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = [Xvalue1, Xvalue2, Xvalue3];
      var yValues = [Yvalue1, Yvalue2, Yvalue3];
      //var yValues = [80,55];
      var barColors = [
        "#b91d47",
        "#00aba9"
      ];

      var chart = new Chart("myChartZ", {
        type: "bar",
        data: {
          labels: [Xvalue1, Xvalue2, Xvalue3],
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          onClick(e) {
          var activePoints = chart.getElementsAtEvent(e);
          var selectedIndex = activePoints[0]._index; 
          alert(chart.data.labels[selectedIndex]);
          //console.log(chart.data.labels[selectedIndex]);    
          },
          responsive: true,
          legend: {
            display: false
         },
         scales: {
            yAxes: [{
              scaleLabel: {
                display: true,
                labelString: 'Operating System'
              }
            }],
            xAxes: [{
              scaleLabel: {
                display: true,
                labelString: 'Operating System'
              }
            }]
          }
        }
      });
      </script>
</div>


<!-- <table class="table-bordered">
    <thead>
        <tr>
            <td>App ID</td><td>Release Date</td><td>Is English</td><td>Developer</td><td>Publisher</td><td>Status</td><td>Platforms</td><td>Age Restriction</td><td>Is Physical</td>
            <td>Units Sold</td><td>Price</td><td>Categories</td><td>Genres</td><td>Achievements</td><td>Positive Ratings</td><td>Negative Ratings</td><td>Tags</td>
            <td>Avg Playtime</td><td>Median Playtime</td><td>Units Available</td>
        </tr>
    </thead>
    <tbody>
        <!-- <?php foreach($view->gameDataSet as $gameData) {
            echo ' <tr> <td>' . $gameData->getAppID() . '</td> <td>' .
            $gameData->getReleaseDate() . '</td> <td>' .
            $gameData->getIsEnglish() . '</td> <td>' .
            $gameData->getDeveloper() . '</td> <td>' .
            $gameData->getPublisher() . '</td> <td>' .
            $gameData->getStatus() . '</td> <td>' .
            $gameData->getPlatforms() . '</td> <td>' .
            $gameData->getRequiredAge() . '</td> <td>' .
            $gameData->getIsPhysical() . '</td> <td>' .
            $gameData->getUnitsSold() . '</td> <td>' . 
            $gameData->getPrice() . '</td> <td>' . 
            $gameData->getCategories() . '</td> <td>' .
            $gameData->getGenres() . '</td> <td>' .
            $gameData->getAchievements() . '</td> <td>' .
            $gameData->getPositiveRatings() . '</td> <td>' .
            $gameData->getNegativeRatings() . '</td> <td>' .
            $gameData->getTags() . '</td> <td>' .
            $gameData->getAveragePlaytime() . '</td> <td>' .
            $gameData->getMedianPlaytime() . '</td> <td>' .
            $gameData->getUnitsAvailable() . '</td></tr>';
            
        }
        ?> -->
    </tbody>
</table> -->
<!-- Top Developer-->
<script type="text/javascript">  
        <?php
            $yValue=1;
                foreach($view->publisherDataSet as $publisherData)
              {
                echo'var Yvalue' . $yValue . '  = "' . $publisherData->getGamesPerPublisher() . '";';
                $yValue++;
              }
              $xValue=1;
              foreach($view->publisherDataSet as $publisherData)
            {
              echo'var Xvalue' . $xValue . '  = "' . $publisherData->getGamesPerPublisher() . '";';
              $xValue++;
            }
          ?>
      </script>
      <div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
      <canvas id="myChart" style="width:100%;max-width:600px"></canvas>

      <script>
      var xValues = [Xvalue1, Xvalue2, Xvalue3, Xvalue4, Xvalue5];
      var yValues = [Yvalue1, Yvalue2, Yvalue3, Yvalue4, Yvalue5];
      //var yValues = [80,55];
      var barColors = [
        "#b91d47",
        "#00aba9"
      ];

      new Chart("myChart", {
        type: "bar",
        data: {
          labels: xValues,
          datasets: [{
            backgroundColor: barColors,
            data: yValues
          }]
        },
        options: {
          responsive: true,
          legend: {
            display: false
         },
         scales: {
            yAxes: [{
              scaleLabel: {
                display: true,
                labelString: 'Game Units Sold'
              }
            }],
            xAxes: [{
              scaleLabel: {
                display: true,
                labelString: 'Genre'
              }
            }]
          }
        }
      });
      </script>
</div>
<!-- Playtime pie chart-->
<div>
<script type="text/javascript">
    var YvalueC = "<?php Print($gameData->getAveragePlaytime()); ?>";
    var YvalueD = "<?php Print($gameData->getMedianPlaytime()); ?>";
</script>

</div>
    
<canvas id="myChartB" style="width:100%;max-width:600px"></canvas>

<script>
var xValues = ["Average Playtime", "Median Playtime"];
var yValues = [YvalueC, YvalueD];
//var yValues = [80,55];
var barColors = [
  "#b91d47",
  "#00aba9"
];

var chartb = new Chart("myChartB", {
  type: "pie",
  data: {
    labels: ["Average Playtime", "Median Playtime"],
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    onClick(e) {
          var activePoints = chart.getElementsAtEventForMode(e, 'nearest', {
        intersect: true
      }, false);
          var selectedIndex = activePoints[0]._index; 
          alert(chartb.data.labels[selectedIndex]);
          //console.log(chart.data.labels[selectedIndex]);    
          },
    title: {
      display: true,
      text: "Playtime"
    }
  }
});
</script>
</div>
<!-- Units  chart-->
<div>
<script type="text/javascript">
    var YvalueD = "<?php Print($gameData->getUnitsSold()); ?>";
    var YvalueC = "<?php Print($gameData->getUnitsAvailable()); ?>";
</script>

<div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<canvas id="myChartC" style="width:100%;max-width:600px"></canvas>

<script>
var xValues = ["Units Sold", "Units Available"];
var yValues = [YvalueC, YvalueD];
//var yValues = [80,55];
var barColors = [
  "#39ff14",
  "#18191a"
];

new Chart("myChartC", {
  type: "doughnut",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    title: {
      display: true,
      text: "Playtime"
    }
  }
});
</script>
</div>





<div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<canvas id="myChartD" style="width:100%;max-width:600px"></canvas>

<script>
var xValues = ["Units Sold", "Units Available"];
var yValues = [YvalueC, YvalueD];
//var yValues = [80,55];
var barColors = [
  "#b91d47",
  "#39ff14"
];

new Chart("myChartD", {
  type: "line",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    title: {
      display: true,
      text: "Playtime"
    }
  }
});
</script>
</div>

<div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<canvas id="myChartD" style="width:100%;max-width:600px"></canvas>

<script>
var xValues = ["Units Sold", "Units Available"];
var yValues = [YvalueC, YvalueD];
//var yValues = [80,55];
var barColors = [
  "#b91d47",
  "#39ff14"
];

new Chart("myChartE", {
  type: "line",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    title: {
      display: true,
      text: "Playtime"
    }
  }
});
</script>
</div>

<div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<canvas id="myChartF" style="width:100%;max-width:600px"></canvas>

<script>
var YvalueD = "<?php Print($gameData->getUnitsSold()); ?>";
var YvalueA = "<?php print($gameData->getAchievements()) ?>";
var YvalueB = "<?php print($gameData->getPositiveRatings()) ?>";
var YvalueC = "<?php print($gameData->getNegativeRatings()) ?>";
var YvalueD = "<?php print($gameData->getAveragePlaytime()) ?>";
var YvalueE = "<?php print($gameData->getMedianPlaytime()) ?>";
var YvalueF = "<?php print($gameData->getUnitsAvailable()) ?>";
var YvalueG = "<?php print($gameData->getUnitsSold()) ?>";

var xValues = ["Achievements", "Positive Reviews", "Negative Reviews", "Average Playtime", "Median Playtime", "Units Available", "Units Sold"];
var yValues = [YvalueA, YvalueB, YvalueC, YvalueD, YvalueE, YvalueF, YvalueG];
                
var barColors = [
  "#b91d47",
  "#00aba9",
  "#00aba9",
  "#00aba9",
  "#00aba9",
  "#00aba9",
  "#00aba9"
];

new Chart("myChartF", {
  type: "bar",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    scales: {
      yAxes: [{
        type: 'logarithmic',
      }],
    }
    
  }
});
</script>
</div>



<div class="container-xxl">
<?php 
        $index= 1;
        foreach($view->gameDataSet as $gameData) {
                echo '<div class="graph">';
                echo '<div><h5>App ID</h5><p>' . $gameData->getAppID() . '</p></div>';
                //Start of JS
                echo '<script type="text/javascript">
                var YvalueA = "' . $gameData->getAchievements(). '";
                var YvalueB = "' . $gameData->getPositiveRatings() . '";
                var YvalueC = "' . $gameData->getNegativeRatings() . '";
                var YvalueD = "' . $gameData->getAveragePlaytime() . '";
                var YvalueE = "' . $gameData->getMedianPlaytime() . '";
                var YvalueF = "' . $gameData->getUnitsAvailable() . '";
                var YvalueG = "' . $gameData->getUnitsSold() . '";
                </script>';
                echo '<div >
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
                <canvas id="myChart' . $index . '" style="width:100%;max-width:300px"></canvas>
                
                <script>
                var xValues = ["Achievements", "Positive Reviews", "Negative Reviews", "Average Playtime", "Median Playtime", "Units Available", "Units Sold"];
                var yValues = [YvalueA, YvalueB, YvalueC, YvalueD, YvalueE, YvalueF, YvalueG];
                
                var barColors = [
                "#b91d47",
                "#00aba9",
                "#00aba9",
                "#00aba9",
                "#00aba9",
                "#00aba9",
                "#00aba9"
                ];
                
                new Chart("myChart' . $index . '", {
                type: "bar",
                data: {
                labels: xValues,
                datasets: [{
                backgroundColor: barColors,
                data: yValues
                }]
                },
                options: {
                title: {
                display: true,
                text: "Positive vs negative reviews"
                }
                }
                });
                </script></div>';
                


                //End of JS
            echo '</div>';
            $index++;
            
        }
        ?>
    </div>












    <div class="container-xxl">
<?php 
        $index= 1;
        foreach($view->publisherDataSet as $publisherData) {
                echo '<div class="graph">';
                echo '<div><h5>App ID</h5><p>' . $gameData->getAppID() . '</p></div>';
                //Start of JS
                echo '<script type="text/javascript">
                var YvalueA = "' . $gameData->getAchievements(). '";
                var YvalueB = "' . $gameData->getPositiveRatings() . '";
                var YvalueC = "' . $gameData->getNegativeRatings() . '";
                var YvalueD = "' . $gameData->getAveragePlaytime() . '";
                var YvalueE = "' . $gameData->getMedianPlaytime() . '";
                var YvalueF = "' . $gameData->getUnitsAvailable() . '";
                var YvalueG = "' . $gameData->getUnitsSold() . '";
                </script>';
                echo '<div >
                <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
                <canvas id="myChart' . $index . '" style="width:100%;max-width:300px"></canvas>
                
                <script>
                var xValues = ["Achievements", "Positive Reviews", "Negative Reviews", "Average Playtime", "Median Playtime", "Units Available", "Units Sold"];
                var yValues = [YvalueA, YvalueB, YvalueC, YvalueD, YvalueE, YvalueF, YvalueG];
                
                var barColors = [
                "#b91d47",
                "#00aba9",
                "#00aba9",
                "#00aba9",
                "#00aba9",
                "#00aba9",
                "#00aba9"
                ];
                
                new Chart("myChart' . $index . '", {
                type: "bar",
                data: {
                labels: xValues,
                datasets: [{
                backgroundColor: barColors,
                data: yValues
                }]
                },
                options: {
                title: {
                display: true,
                text: "Positive vs negative reviews"
                }
                }
                });
                </script></div>';
                


                //End of JS
            echo '</div>';
            $index++;
            
        }
        ?>
    </div>

    <?php
                $yValue=1;
                foreach($view->genreDataSet as $genreData)
              {
                $y . $yValue . $genreData->getGameNumber() ;
                $yValue++;
              }
              $xValue=1;
              foreach($view->genreDataSet as $genreData)
            {
              $x . $xValue . $genreData->getGenreName() ;
              $xValue++;
            }
            echo '<h3>' . $y1 .. $y2 . $y3 . $y4 . $y5  '</h3>'
          ?>
          

<?php require('Views/template/footer.phtml'); ?>


