<?php
require_once('Views/template/header.phtml');
require_once("Views/template/filters.phtml");

?>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
<script type="text/javascript" src="/js/custom-js.js"></script>
<div id="full"></div>
    <div class="row justify-content-md-center m-0 animate__animated animate__fadeInUp animate__delay-07s" onload="destroy()">
        <div class="row font-white m-auto">
            <span class="col-sm-7 mx-1"></span>
            <button id="selectAll" class="col-sm-2 btn btn-outline-light m-2 font-xs mx-auto my-2" onclick="selectAll()">Select all</button>
            <div id="optionsCon" class="col-sm-2 p-0">
                <button class="btn btn-outline-light m-2 font-xs w-100 mx-auto my-2" onclick="showOptions()">Edit selected</button>
                <div id="options" class="hide-options w-100 bg-grey">
                    <?php
                    $index=0;
                    foreach ($view->labels as $value) {
                        if ($value == "Status") {
                            echo '<div>
                            <button class="btn btn-light m-2 noRadius font-xs d-block w-100 mx-auto my-0 py-2 but-hover border-0" onclick="showOptionButton(';
                            echo "'optionButton" . $index . "')";
                            echo '"/>' . $value . '</button>
                            <div id="optionButton' . $index . '" class="hide-options my-2 text-center">';
                            $status = array("In-development", "Restricted", "Archived", "Live", "Banned", "Beta");
                            echo '<select list="status" class="font-white col-sm-4 w-75 bg-grey mx-auto my-2" name="status" id="item' . $index . '">';
                            foreach ($status as $value2) {
                                echo '<option value="' . $value2 . '"';
                                echo '>' . $value2 . '</option>';
                            }
                            echo '</select><button class="btn btn-success m-2 font-xs d-block w-75 mx-auto my-0 py-2 but-hover border-0" onclick="editSelected(';
                            echo "'" . $value . "',document.getElementById('item" . $index . "').value)";
                            echo '"/>Apply</button>
                            </div>
                            </div>
                            ';
                            $index++;
                        } elseif ($value == "Categories" || $value == "Tags" || $value == "Genres" || $value == "Developer") {
                            echo '
                            <div>
                            <button class="btn btn-light m-2 noRadius font-xs d-block w-100 mx-auto my-0 py-2 but-hover border-0" onclick="showOptionButton(';
                                echo "'optionButton" . $index . "')";
                                echo '"/>' . $value . '</button>
                            <div id="optionButton' . $index . '" class="hide-options my-2">
                            <input class="w-75 my-3 mx-auto d-block col-sm-12" id="item' . $index . '" type="text" />
                            
                            <button class="btn btn-danger m-2 font-xs d-block w-75 mx-auto my-2 py-2 but-hover border-0" onclick="editSelected(';
                                echo "'" . $value . "',document.getElementById('item" . $index . "').value, 'Remove')";
                                echo '"/>Remove</button>

                                    <button class="btn btn-success m-2 font-xs d-block w-75 mx-auto my-2 py-2 but-hover border-0" onclick="editSelected(';
                                echo "'" . $value . "',document.getElementById('item" . $index . "').value, 'Add')";
                                echo '"/>Add</button>
                            </div>
                            </div>
                            ';
                            $index++;
                        }
                        else {
                            echo '
                            <div>
                            <button class="btn btn-light m-2 noRadius font-xs d-block w-100 mx-auto my-0 py-2 but-hover border-0" onclick="showOptionButton(';
                                echo "'optionButton" . $index . "')";
                                echo '"/>' . $value . '</button>
                            <div id="optionButton' . $index . '" class="hide-options my-2">
                            <input class="w-75 my-3 mx-auto d-block" id="item' . $index . '" type="text" />
                            <button class="btn btn-success m-2 font-xs d-block w-75 mx-auto my-0 py-2 but-hover border-0" onclick="editSelected(';
                                echo "'" . $value . "',document.getElementById('item" . $index . "').value)";
                                echo '"/>Apply</button>
                            </div>
                            </div>
                            ';
                            $index++;
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
        <div id="tiles" class="row m-auto">
        </div>
        <div id="loading" class="center">
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
        </div>
        <h3 id="end" class="d-none">End of results</h3>
    </div>
</div>
<?php 
require_once('Views/template/footer.phtml');

if (isset($LazyLoad)){
    echo '<script>
        var load = new LazyLoad("'.$LazyLoad->url.'", "'.$LazyLoad->data.'", "'.$LazyLoad->type.'", '.$LazyLoad->xValues.', '.$LazyLoad->chart.', '.$LazyLoad->legend.');
        const url = "'.$view->url.'";
    </script>';
}
?>