<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/my-style.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-grid.css" rel="stylesheet">
    <link href="/css/bootstrap-grid.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-reboot.css" rel="stylesheet">
    <link href="/css/bootstrap-reboot.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-utilities.css" rel="stylesheet">
    <link href="/css/bootstrap-utilities.rtl.css" rel="stylesheet">

    <title><?php echo $view->pageTitle; ?></title>
</head>
<body role="document">
    <header class="d-flex mt-1">
        <button id="menu-button"><span class="bi bi-list search-icon"><span class="arrow-right"></span></button>
        <form action="/search.php" method="post" class="form-check-inline mx-auto">
            <div class="input-group">
                <input id="search-bar" name="searchText" type="text" placeholder="Search by ID" aria-label="Search" />
                <button type="submit" name="Search" id="search-bar-addOn" value=""><span class="bi bi-search bright"></span></button>
            </div>
        </form>
        <button id="filters-button"> <span class="bi bi-filter-circle-fill bright"></span></button>
    </header>


