<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/my-style.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-grid.css" rel="stylesheet">
    <link href="/css/bootstrap-grid.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-reboot.css" rel="stylesheet">
    <link href="/css/bootstrap-reboot.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-utilities.css" rel="stylesheet">
    <link href="/css/bootstrap-utilities.rtl.css" rel="stylesheet">

    <title><?php echo $view->pageTitle; ?></title>
</head>
<body role="document">
   <header class="sticky-top">
       <nav class="navbar navbar-light d-flex justify-content-between">
           <button onclick="slideIn()" class="btn bg-blue radius-right"><span class="bi bi-list font-grey display-5 "></span></button>
           <ul id="slider" class="hide navbar-nav bg-blue font-grey d-flex flex-lg-row radius-right p-3">
               <li class="nav-item mx-3 my-auto"><a class="nav-link" href="../../proofReader.php">Proof-reader</a></li>
               <li class="nav-item mx-3 my-auto"><a class="nav-link" href="../../salesRep.php">Sales Representative</a></li>
               <li class="nav-item mx-3 my-auto"><a class="nav-link" href="../../developer.php">Developer</a></li>
               <li class="nav-item mx-3 my-auto"><a class="nav-link" href="../../dataAnalyst.php">Data analyst</a></li>
               <li class="nav-item mx-auto my-auto"><button onclick="slideOut()" class="btn"><span class="bi bi-x font-22"></span></button></li>
           </ul>
           <form action="/search.php" method="post" class="form-check-inline col-md-4 mx-auto">
               <div class="input-group glow-border">
                   <input class="form-control px-2 bg-grey font-blue radius-left" name="searchText" type="text" placeholder="Search" aria-label="Search" />
                   <div class="input-group-append">
                       <button type="submit" name="Search" class="input-group-text bg-grey radius-right " id="basic-addon1" value="Search">
                           <span class="bi bi-search font-blue font-22">
                       </button>
                   </div>
               </div>
           </form>
           <button class="btn mx-3" onclick="showFilters()"><span class="bi bi-filter-circle-fill display-5 font-blue"></span></button>
       </nav>
   </header>
<main>
    <div id="filters" class="bg-shadow hide-filters">
    <div class="filer-container">
        <button onclick="showReleaseDate()" class="filter-item">Release date<span class="bi bi-arrow-down font-white"></span></button>
        <div id="release-date" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showEnglish()" class="filter-item">English<span class="bi bi-arrow-down font-white"></span></button>
        <div id="english" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showDeveloper()" class="filter-item">Developer<span class="bi bi-arrow-down font-white"></span></button>
        <div id="developer" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showPublisher()" class="filter-item">Publisher<span class="bi bi-arrow-down font-white"></span></button>
        <div id="publisher" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showStatus()" class="filter-item">Status<span class="bi bi-arrow-down font-white"></span></button>
        <div id="status" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showRequiredAge()" class="filter-item">Required age<span class="bi bi-arrow-down font-white"></span></button>
        <div id="required-age" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showCategories()" class="filter-item">Categories<span class="bi bi-arrow-down font-white"></span></button>
        <div id="categories" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showGenres()" class="filter-item">Genres<span class="bi bi-arrow-down font-white"></span></button>
        <div id="genres" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showTags()" class="filter-item">Tags<span class="bi bi-arrow-down font-white"></span></button>
        <div id="tags" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showAchievements()" class="filter-item">Achievements<span class="bi bi-arrow-down font-white"></span></button>
        <div id="achievements" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showPositiveRatings()" class="filter-item">Positive ratings<span class="bi bi-arrow-down font-white"></span></button>
        <div id="positive-ratings" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showNegativeRatings()" class="filter-item">Negative ratings<span class="bi bi-arrow-down font-white"></span></button>
        <div id="negative-ratings" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showAveragePlaytime()" class="filter-item">Average playtime<span class="bi bi-arrow-down font-white"></span></button>
        <div id="average-playtime" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showMedianPlaytime()" class="filter-item">Median playtime<span class="bi bi-arrow-down font-white"></span></button>
        <div id="median-playtime" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showPhysical()" class="filter-item">Physical<span class="bi bi-arrow-down font-white"></span></button>
        <div id="physical" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showUnitsAvailable()" class="filter-item">Units available<span class="bi bi-arrow-down font-white"></span></button>
        <div id="units-available" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showUnitsSold()" class="filter-item">Units sold<span class="bi bi-arrow-down font-white"></span></button>
        <div id="units-sold" class="hide-slide">
            <p>Release date</p>
        </div>
        <button onclick="showPrice()" class="filter-item">Price<span class="bi bi-arrow-down font-white"></span></button>
        <div id="price" class="hide-slide">
            <p>Release date</p>
        </div>
        <div class="d-flex justify-content-between m-5">
        <button class="btn bg-bright" onclick="hideFilters()">Back</button>
        <button class="btn font-blue bg-bright">Apply</button>
        </div>
    </div>
    </div>
