<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/my-style.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-grid.css" rel="stylesheet">
    <link href="/css/bootstrap-grid.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-reboot.css" rel="stylesheet">
    <link href="/css/bootstrap-reboot.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-utilities.css" rel="stylesheet">
    <link href="/css/bootstrap-utilities.rtl.css" rel="stylesheet">
    <link href="/css/bootstrap-tagsinput.css" rel="stylesheet">
    <link href="/css/bootstrap-tagsinput.less" rel="stylesheet">
    <link href="/css/animate.css" rel="stylesheet">

    <title><?php echo $view->pageTitle; ?></title>
</head>
<body role="document">
   <header class="sticky-top bg-grey">
       <nav class="d-flex">
           <button onclick="slideIn()" id="menu-button" class="btn bg-blue radius-right p-0 my-auto"><span class="bi bi-list font-grey font-28 px-3 white-hover"></span></button>
           <?php
           echo '<span class="font-blue mx-3 my-auto font-xs" id="page-title">'.$view->pageTitle.'</span>';
           ?>

           <ul id="slider" class="hide navbar-nav bg-blue font-grey d-flex flex-lg-row radius-right">
                <li class="mx-auto my-auto"><a class="font-grey m-1" href="/index.php"><span class="bi bi-house-door-fill font-22 mx-3 white-hover"></span></a></li>
               <li class="mx-3 my-auto"><a class="font-grey" href="/proofReader.php">Proof Reader</a></li>
               <li class="mx-3 my-auto"><a class="font-grey" href="/salesRep.php">Sales Representative</a></li>
               <li class="mx-3 my-auto"><a class="font-grey" href="/developer.php">Developer</a></li>
               <li class="mx-3 my-auto"><a class="font-grey" href="/dataAnalyst.php">Data Analyst</a></li>
               <li class="mx-auto my-auto"><button onclick="slideOut()" class="btn"><span class="bi bi-x font-22 white-hover"></span></button></li>
           </ul>
<?php //require_once("filters.phtml"); ?>         